"""Strings."""
no_input = "Please provide valid input."
invalid_secret = "Please check if secret is valid."
added_secret = "Added secret."
duplicate_secret = "Secret already exists."
user_fetch_failed = "Unable to get user details."
invalid_setting = "Invalid setting name"
file_process_failed = "Unable to process URI file."
