# Generated by Django 4.2.3 on 2023-07-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('suspended', 'SUSPENDED'), ('temporarily banned', 'TEMP_BANNED')], default='active', max_length=20)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.TextField(unique=True)),
                ('issuer', models.CharField(max_length=256)),
                ('account_id', models.CharField(blank=True, max_length=256)),
                ('digits', models.IntegerField(default=6)),
                ('period', models.IntegerField(default=30)),
                ('algorithm', models.CharField(default='SHA1', max_length=256)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlitedb.user')),
            ],
            options={
                'db_table': 'secret',
            },
        ),
    ]
