"""Strings."""
no_input = "Please provide valid input."
invalid_secret = "Please check if secret is valid."
added_secret = "Added secret."
duplicate_secret = "Secret already exists."
user_fetch_failed = "Unable to get user details."
invalid_setting = "Invalid setting name"
file_process_failed = "Terminating URI file processing."
processing_file = "Processing file."
invalid_page_size = "Invalid value for page size."
page_size_updated = "Page size successfully updated."
no_result = "No result."
